# PyTorch Code Examples

## Tensors and Variables

In [1]:
import torch


* pytorch Tensors는 numpy's arrays와 비슷하게 동작한다

In [2]:
a = torch.Tensor([[1,2],[3,4]])
print(a)


tensor([[1., 2.],
        [3., 4.]])


In [3]:
print(a**2)


tensor([[ 1.,  4.],
        [ 9., 16.]])


* pytorch Variables는 a tensor 그리고 record operations 를 동작하게 묶어준다.
* backprop 동작을 하게 만들어준다

In [4]:
from torch.autograd import Variable


In [5]:
a = Variable(torch.Tensor([[1,2],[3,4]]), requires_grad=True)
print(a) # torch.FloatTensor of size 2x2


tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


In [6]:
y = torch.sum(a**2)
print(y) # torch.FloatTensor of size 1


tensor(30., grad_fn=<SumBackward0>)


In [7]:
y.backward() # compute gradients of y wrt a
print(a.grad) # print dy/da_ij = 2 * a_ij for a_11, a_12, a_21, a_22

tensor([[2., 4.],
        [6., 8.]])


## Core Traning Step

* pass a batch of inputs through the model / batch 인풋을 모델에 넣기
* calculate the loss / 로스 계산
* calculate backprop / backprop 계산
* update the parameters / 파라미터 업데이트

In [ ]:
output_batch = model(train_batch) # compute model output
loss = loss_fn(output_batch, labels_batch) # calculate loss

optimizer.zero_grad() # clear previous gradients
loss.backward() # comput gradients of all variables wrt loss

optimizer.step() # perform updates using claculated gradients